% Soluzione esercizio 3

thisDir = fileparts(mfilename('fullpath'));
labDir = fileparts(thisDir);
dbPath = fullfile(labDir, 'dati', 'lab07_biomed.db');

conn = sqlite(dbPath);
q = [ ...
    'SELECT p.id, p.cognome, COUNT(e.id) AS n_esami ' ...
    'FROM pazienti p ' ...
    'LEFT JOIN esami_lab e ON e.paziente_id = p.id ' ...
    'GROUP BY p.id, p.cognome ' ...
    'ORDER BY p.id;' ...
    ];
T = fetch(conn, q);
close(conn);
disp(T);
