% Soluzione esercizio 5

thisDir = fileparts(mfilename('fullpath'));
labDir = fileparts(thisDir);
dbPath = fullfile(labDir, 'dati', 'lab07_biomed.db');

conn = sqlite(dbPath);
T = table( ...
    [2; 2], ...
    {'LDH'; 'PCR'}, ...
    [230; 0.4], ...
    {'U/L'; 'mg/dL'}, ...
    {'2025-05-10'; '2025-05-10'}, ...
    'VariableNames', {'paziente_id', 'nome_esame', 'valore', 'unita', 'data_esame'} ...
    );
sqlwrite(conn, 'esami_lab', T);
T2 = fetch(conn, [ ...
    'SELECT * FROM esami_lab WHERE paziente_id = 2 ' ...
    'AND nome_esame IN (''LDH'', ''PCR'') ORDER BY nome_esame;' ...
    ]);
close(conn);
disp(T2);
