% lab07_create_fresh_database.m
% Script semplice (senza function) che ricrea il database da zero.
%
% Uso tipico da un altro script:
%   run(fullfile(cartellaLab, 'codice', 'lab07_create_fresh_database.m'));
%   percorsoDb = dbPath;
%
% Variabile esportata nello workspace chiamante:
%   dbPath  -> percorso completo del file .db creato

cartellaScript = fileparts(mfilename('fullpath'));
labDir = fileparts(cartellaScript);
datiDir = fullfile(labDir, 'dati');
if ~isfolder(datiDir)
    mkdir(datiDir);
end

dbPath = fullfile(datiDir, 'lab07_biomed.db');

if exist('conn', 'var')
    try
        close(conn);
    catch
    end
    clear conn
end

if isfile(dbPath)
    delete(dbPath);
end

connInit = sqlite(dbPath, 'create');
execute(connInit, 'PRAGMA foreign_keys=ON;');

execute(connInit, [ ...
    'CREATE TABLE reparti (' ...
    'id INTEGER PRIMARY KEY AUTOINCREMENT,' ...
    'nome TEXT NOT NULL,' ...
    'piano INTEGER,' ...
    'descrizione TEXT' ...
    ');' ...
    ]);

execute(connInit, [ ...
    'CREATE TABLE medici (' ...
    'id INTEGER PRIMARY KEY AUTOINCREMENT,' ...
    'nome TEXT NOT NULL,' ...
    'cognome TEXT NOT NULL,' ...
    'reparto_id INTEGER NOT NULL REFERENCES reparti(id) ON DELETE RESTRICT,' ...
    'specialita TEXT' ...
    ');' ...
    ]);

execute(connInit, [ ...
    'CREATE TABLE pazienti (' ...
    'id INTEGER PRIMARY KEY AUTOINCREMENT,' ...
    'nome TEXT NOT NULL,' ...
    'cognome TEXT NOT NULL,' ...
    'anno_nascita INTEGER,' ...
    'sesso TEXT CHECK (sesso IN (''M'', ''F'', ''X'')) DEFAULT ''X'',' ...
    'reparto_id INTEGER REFERENCES reparti(id) ON DELETE SET NULL' ...
    ');' ...
    ]);

execute(connInit, [ ...
    'CREATE TABLE tipi_esame (' ...
    'id INTEGER PRIMARY KEY AUTOINCREMENT,' ...
    'codice TEXT NOT NULL UNIQUE,' ...
    'nome TEXT NOT NULL,' ...
    'unita_ref TEXT NOT NULL,' ...
    'valore_min REAL,' ...
    'valore_max REAL' ...
    ');' ...
    ]);

execute(connInit, [ ...
    'CREATE TABLE visite (' ...
    'id INTEGER PRIMARY KEY AUTOINCREMENT,' ...
    'paziente_id INTEGER NOT NULL REFERENCES pazienti(id) ON DELETE CASCADE,' ...
    'medico_id INTEGER NOT NULL REFERENCES medici(id) ON DELETE RESTRICT,' ...
    'data_visita TEXT NOT NULL,' ...
    'motivo TEXT' ...
    ');' ...
    ]);

execute(connInit, [ ...
    'CREATE TABLE esami_lab (' ...
    'id INTEGER PRIMARY KEY AUTOINCREMENT,' ...
    'visita_id INTEGER NOT NULL REFERENCES visite(id) ON DELETE CASCADE,' ...
    'tipo_esame_id INTEGER NOT NULL REFERENCES tipi_esame(id) ON DELETE RESTRICT,' ...
    'valore REAL NOT NULL,' ...
    'unita TEXT NOT NULL,' ...
    'data_risultato TEXT NOT NULL,' ...
    'note TEXT' ...
    ');' ...
    ]);

execute(connInit, [ ...
    'CREATE TABLE audit_log (' ...
    'id INTEGER PRIMARY KEY AUTOINCREMENT,' ...
    'tabella TEXT NOT NULL,' ...
    'operazione TEXT NOT NULL,' ...
    'riga_id INTEGER,' ...
    'descrizione TEXT,' ...
    'data_evento TEXT DEFAULT CURRENT_TIMESTAMP' ...
    ');' ...
    ]);

execute(connInit, 'INSERT INTO reparti (nome, piano, descrizione) VALUES (''Biochimica clinica'', 2, ''Laboratorio centrale: biochimica, immunologia, ormoni'');');
execute(connInit, 'INSERT INTO reparti (nome, piano, descrizione) VALUES (''Ematologia'', 4, ''Emocromo, coagulazione, emoglobinurie'');');
execute(connInit, 'INSERT INTO reparti (nome, piano, descrizione) VALUES (''Medicina interna'', 3, ''Degenza e follow-up metabolico'');');
execute(connInit, 'INSERT INTO reparti (nome, piano, descrizione) VALUES (''Endocrinologia'', 5, ''Ambulatorio diabete, tiroide e metabolismo'');');
execute(connInit, 'INSERT INTO reparti (nome, piano, descrizione) VALUES (''Pronto soccorso'', 0, ''Accessi urgenti e prime valutazioni cliniche'');');

execute(connInit, 'INSERT INTO medici (nome, cognome, reparto_id, specialita) VALUES (''Anna'', ''Rossi'', 1, ''Patologia clinica'');');
execute(connInit, 'INSERT INTO medici (nome, cognome, reparto_id, specialita) VALUES (''Luca'', ''Gallo'', 1, ''Endocrinologia e diabetologia'');');
execute(connInit, 'INSERT INTO medici (nome, cognome, reparto_id, specialita) VALUES (''Chiara'', ''Marta'', 3, ''Medicina interna'');');
execute(connInit, 'INSERT INTO medici (nome, cognome, reparto_id, specialita) VALUES (''Filippo'', ''Neri'', 2, ''Ematologia clinica'');');
execute(connInit, 'INSERT INTO medici (nome, cognome, reparto_id, specialita) VALUES (''Serena'', ''Conti'', 4, ''Endocrinologia'');');
execute(connInit, 'INSERT INTO medici (nome, cognome, reparto_id, specialita) VALUES (''Davide'', ''Russo'', 5, ''Medicina d urgenza'');');

execute(connInit, 'INSERT INTO pazienti (nome, cognome, anno_nascita, sesso, reparto_id) VALUES (''Giulia'', ''Verdi'', 1992, ''F'', 1);');
execute(connInit, 'INSERT INTO pazienti (nome, cognome, anno_nascita, sesso, reparto_id) VALUES (''Marco'', ''Bianchi'', 1985, ''M'', 1);');
execute(connInit, 'INSERT INTO pazienti (nome, cognome, anno_nascita, sesso, reparto_id) VALUES (''Laura'', ''Neri'', 2001, ''F'', 2);');
execute(connInit, 'INSERT INTO pazienti (nome, cognome, anno_nascita, sesso, reparto_id) VALUES (''Paolo'', ''Blu'', 1978, ''M'', 3);');
execute(connInit, 'INSERT INTO pazienti (nome, cognome, anno_nascita, sesso, reparto_id) VALUES (''Sara'', ''Romano'', 1968, ''F'', 4);');
execute(connInit, 'INSERT INTO pazienti (nome, cognome, anno_nascita, sesso, reparto_id) VALUES (''Ahmed'', ''Khan'', 1998, ''M'', 5);');
execute(connInit, 'INSERT INTO pazienti (nome, cognome, anno_nascita, sesso, reparto_id) VALUES (''Elena'', ''Costa'', 1955, ''F'', 3);');
execute(connInit, 'INSERT INTO pazienti (nome, cognome, anno_nascita, sesso, reparto_id) VALUES (''Marta'', ''Greco'', 2010, ''F'', 2);');
execute(connInit, 'INSERT INTO pazienti (nome, cognome, anno_nascita, sesso, reparto_id) VALUES (''Nicola'', ''Ferrari'', 1970, ''M'', 4);');
execute(connInit, 'INSERT INTO pazienti (nome, cognome, anno_nascita, sesso, reparto_id) VALUES (''Irene'', ''Moretti'', 1989, ''F'', NULL);');

execute(connInit, 'INSERT INTO tipi_esame (codice, nome, unita_ref, valore_min, valore_max) VALUES (''GLU'', ''Glicemia'', ''mg/dL'', 70, 100);');
execute(connInit, 'INSERT INTO tipi_esame (codice, nome, unita_ref, valore_min, valore_max) VALUES (''HGB'', ''Emoglobina'', ''g/dL'', 12.0, 16.0);');
execute(connInit, 'INSERT INTO tipi_esame (codice, nome, unita_ref, valore_min, valore_max) VALUES (''CHOL'', ''Colesterolo totale'', ''mg/dL'', NULL, 200);');
execute(connInit, 'INSERT INTO tipi_esame (codice, nome, unita_ref, valore_min, valore_max) VALUES (''PCR'', ''PCR quantitativa'', ''mg/dL'', NULL, 5);');
execute(connInit, 'INSERT INTO tipi_esame (codice, nome, unita_ref, valore_min, valore_max) VALUES (''LDH'', ''LDH'', ''U/L'', 140, 280);');
execute(connInit, 'INSERT INTO tipi_esame (codice, nome, unita_ref, valore_min, valore_max) VALUES (''FERR'', ''Ferritina'', ''ng/mL'', 20, 300);');
execute(connInit, 'INSERT INTO tipi_esame (codice, nome, unita_ref, valore_min, valore_max) VALUES (''CREA'', ''Creatinina'', ''umol/L'', 59, 104);');
execute(connInit, 'INSERT INTO tipi_esame (codice, nome, unita_ref, valore_min, valore_max) VALUES (''PAS'', ''Pressione sistolica'', ''mmHg'', 90, 140);');
execute(connInit, 'INSERT INTO tipi_esame (codice, nome, unita_ref, valore_min, valore_max) VALUES (''WBC'', ''Leucociti'', ''10^9/L'', 4.0, 10.0);');
execute(connInit, 'INSERT INTO tipi_esame (codice, nome, unita_ref, valore_min, valore_max) VALUES (''PLT'', ''Piastrine'', ''10^9/L'', 150, 450);');
execute(connInit, 'INSERT INTO tipi_esame (codice, nome, unita_ref, valore_min, valore_max) VALUES (''ALT'', ''ALT'', ''U/L'', NULL, 45);');
execute(connInit, 'INSERT INTO tipi_esame (codice, nome, unita_ref, valore_min, valore_max) VALUES (''TSH'', ''TSH'', ''mIU/L'', 0.4, 4.0);');
execute(connInit, 'INSERT INTO tipi_esame (codice, nome, unita_ref, valore_min, valore_max) VALUES (''NA'', ''Sodio'', ''mmol/L'', 135, 145);');
execute(connInit, 'INSERT INTO tipi_esame (codice, nome, unita_ref, valore_min, valore_max) VALUES (''K'', ''Potassio'', ''mmol/L'', 3.5, 5.1);');

execute(connInit, 'INSERT INTO visite (paziente_id, medico_id, data_visita, motivo) VALUES (1, 1, ''2025-01-10'', ''Controllo metabolico e profilo lipidico'');');
execute(connInit, 'INSERT INTO visite (paziente_id, medico_id, data_visita, motivo) VALUES (1, 2, ''2025-03-02'', ''Follow-up glicemia e colesterolo'');');
execute(connInit, 'INSERT INTO visite (paziente_id, medico_id, data_visita, motivo) VALUES (2, 1, ''2025-02-15'', ''Primo accesso per iperglicemia'');');
execute(connInit, 'INSERT INTO visite (paziente_id, medico_id, data_visita, motivo) VALUES (3, 3, ''2025-04-01'', ''Screening pre-operatorio'');');
execute(connInit, 'INSERT INTO visite (paziente_id, medico_id, data_visita, motivo) VALUES (4, 4, ''2025-04-05'', ''Controllo post-dimissioni'');');
execute(connInit, 'INSERT INTO visite (paziente_id, medico_id, data_visita, motivo) VALUES (2, 2, ''2025-05-10'', ''Visita ambulatoriale diabetologica'');');
execute(connInit, 'INSERT INTO visite (paziente_id, medico_id, data_visita, motivo) VALUES (5, 5, ''2025-05-12'', ''Controllo tiroideo e metabolismo'');');
execute(connInit, 'INSERT INTO visite (paziente_id, medico_id, data_visita, motivo) VALUES (6, 6, ''2025-05-13'', ''Accesso urgente per disidratazione'');');
execute(connInit, 'INSERT INTO visite (paziente_id, medico_id, data_visita, motivo) VALUES (7, 3, ''2025-05-14'', ''Controllo insufficienza renale lieve'');');
execute(connInit, 'INSERT INTO visite (paziente_id, medico_id, data_visita, motivo) VALUES (8, 4, ''2025-05-15'', ''Emocromo pediatrico di controllo'');');
execute(connInit, 'INSERT INTO visite (paziente_id, medico_id, data_visita, motivo) VALUES (9, 5, ''2025-06-01'', ''Follow-up diabete tipo 2'');');
execute(connInit, 'INSERT INTO visite (paziente_id, medico_id, data_visita, motivo) VALUES (10, 1, ''2025-06-03'', ''Screening generale annuale'');');
execute(connInit, 'INSERT INTO visite (paziente_id, medico_id, data_visita, motivo) VALUES (1, 1, ''2025-06-10'', ''Ricontrollo dopo dieta'');');
execute(connInit, 'INSERT INTO visite (paziente_id, medico_id, data_visita, motivo) VALUES (2, 5, ''2025-06-12'', ''Secondo follow-up glicemico'');');

execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (1, 1, 92.0, ''mg/dL'', ''2025-01-10'', NULL);');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (1, 7, 88.0, ''umol/L'', ''2025-01-10'', ''eGFR stabile'');');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (2, 1, 108.0, ''mg/dL'', ''2025-03-02'', ''a digiuno'');');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (2, 3, 195.0, ''mg/dL'', ''2025-03-02'', NULL);');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (2, 8, 122.0, ''mmHg'', ''2025-03-02'', ''PA al momento del prelievo'');');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (3, 1, 126.0, ''mg/dL'', ''2025-02-15'', NULL);');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (3, 2, 14.1, ''g/dL'', ''2025-02-15'', NULL);');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (4, 1, 88.0, ''mg/dL'', ''2025-04-01'', NULL);');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (4, 8, 118.0, ''mmHg'', ''2025-04-01'', NULL);');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (5, 2, 13.2, ''g/dL'', ''2025-04-05'', NULL);');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (5, 4, 2.1, ''mg/dL'', ''2025-04-05'', ''infiammazione lieve'');');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (1, 3, 178.0, ''mg/dL'', ''2025-01-10'', ''primo campione del profilo'');');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (6, 1, 119.0, ''mg/dL'', ''2025-05-10'', ''controllo a digiuno'');');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (6, 5, 230.0, ''U/L'', ''2025-05-10'', NULL);');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (6, 4, 0.4, ''mg/dL'', ''2025-05-10'', NULL);');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (7, 12, 5.8, ''mIU/L'', ''2025-05-12'', ''TSH lievemente alto'');');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (7, 1, 101.0, ''mg/dL'', ''2025-05-12'', NULL);');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (8, 13, 132.0, ''mmol/L'', ''2025-05-13'', ''iponatriemia lieve'');');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (8, 14, 3.2, ''mmol/L'', ''2025-05-13'', ''potassio basso'');');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (8, 7, 110.0, ''umol/L'', ''2025-05-13'', ''disidratazione sospetta'');');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (9, 7, 118.0, ''umol/L'', ''2025-05-14'', ''sopra range'');');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (9, 13, 139.0, ''mmol/L'', ''2025-05-14'', NULL);');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (9, 14, 4.7, ''mmol/L'', ''2025-05-14'', NULL);');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (10, 9, 7.2, ''10^9/L'', ''2025-05-15'', NULL);');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (10, 10, 310.0, ''10^9/L'', ''2025-05-15'', NULL);');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (10, 2, 12.4, ''g/dL'', ''2025-05-15'', NULL);');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (11, 1, 142.0, ''mg/dL'', ''2025-06-01'', ''valore alto'');');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (11, 3, 222.0, ''mg/dL'', ''2025-06-01'', ''sopra soglia'');');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (11, 6, 340.0, ''ng/mL'', ''2025-06-01'', ''sopra range'');');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (12, 1, 83.0, ''mg/dL'', ''2025-06-03'', NULL);');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (12, 11, 32.0, ''U/L'', ''2025-06-03'', NULL);');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (12, 12, 2.1, ''mIU/L'', ''2025-06-03'', NULL);');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (13, 1, 96.0, ''mg/dL'', ''2025-06-10'', ''miglioramento'');');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (13, 3, 181.0, ''mg/dL'', ''2025-06-10'', NULL);');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (14, 1, 111.0, ''mg/dL'', ''2025-06-12'', ''da ricontrollare'');');
execute(connInit, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (14, 8, 136.0, ''mmHg'', ''2025-06-12'', NULL);');

execute(connInit, 'CREATE INDEX idx_visite_paziente ON visite(paziente_id);');
execute(connInit, 'CREATE INDEX idx_esami_visita ON esami_lab(visita_id);');
execute(connInit, 'CREATE INDEX idx_esami_tipo ON esami_lab(tipo_esame_id);');
execute(connInit, [ ...
    'CREATE VIEW v_esami_completi AS ' ...
    'SELECT e.id AS esame_id, p.cognome, p.nome, v.data_visita, m.cognome AS medico, ' ...
    'r.nome AS reparto, t.codice, t.nome AS esame, e.valore, e.unita, ' ...
    't.valore_min, t.valore_max, e.data_risultato, e.note ' ...
    'FROM esami_lab e ' ...
    'JOIN visite v ON v.id = e.visita_id ' ...
    'JOIN pazienti p ON p.id = v.paziente_id ' ...
    'JOIN medici m ON m.id = v.medico_id ' ...
    'LEFT JOIN reparti r ON r.id = p.reparto_id ' ...
    'JOIN tipi_esame t ON t.id = e.tipo_esame_id;' ...
    ]);

close(connInit);
clear connInit
