function dbPath = lab07_create_fresh_database(labDir)
%LAB07_CREATE_FRESH_DATABASE Ricrea da zero il file SQLite del laboratorio.
%
%   dbPath = lab07_create_fresh_database(labDir)
%   labDir = cartella radice 07-matlab-sqlite-database.
%
%   Schema didattico esteso (6 tabelle):
%   - reparti       : unità organizzative (laboratorio, ematologia, degenza).
%   - medici        : anagrafica medici, FK a reparti (RESTRICT: non si cancella
%                     un reparto se ci sono medici assegnati).
%   - pazienti      : anagrafica; reparto_id opzionale (SET NULL se il reparto sparisce).
%   - tipi_esame    : catalogo test di laboratorio (codice, nome, range di riferimento).
%   - visite        : incontro paziente–medico in data; FK paziente CASCADE (se si
%                     elimina il paziente, spariscono le visite e a catena gli esami).
%   - esami_lab     : risultato numerico; FK visita CASCADE, FK tipo RESTRICT.
%
%   Richiede Database Toolbox: sqlite, execute, close.
%   Glossario: vedi esercizi/es01_apri_db_sqlread.m

    labDir = char(labDir);
    datiDir = fullfile(labDir, 'dati');
    if ~isfolder(datiDir)
        mkdir(datiDir);
    end

    dbPath = fullfile(datiDir, 'lab07_biomed.db');

    if isfile(dbPath)
        try
            delete(dbPath);
        catch ME
            error('lab07:dbDelete', '%s\nChiudi connessioni o programmi che usano il file.', ME.message);
        end
    end

    conn = sqlite(dbPath);
    execute(conn, 'PRAGMA foreign_keys=ON;');

    execute(conn, [ ...
        'CREATE TABLE reparti (' ...
        'id INTEGER PRIMARY KEY AUTOINCREMENT,' ...
        'nome TEXT NOT NULL,' ...
        'piano INTEGER,' ...
        'descrizione TEXT' ...
        ');' ...
        ]);

    execute(conn, [ ...
        'CREATE TABLE medici (' ...
        'id INTEGER PRIMARY KEY AUTOINCREMENT,' ...
        'nome TEXT NOT NULL,' ...
        'cognome TEXT NOT NULL,' ...
        'reparto_id INTEGER NOT NULL REFERENCES reparti(id) ON DELETE RESTRICT,' ...
        'specialita TEXT' ...
        ');' ...
        ]);

    execute(conn, [ ...
        'CREATE TABLE pazienti (' ...
        'id INTEGER PRIMARY KEY AUTOINCREMENT,' ...
        'nome TEXT NOT NULL,' ...
        'cognome TEXT NOT NULL,' ...
        'anno_nascita INTEGER,' ...
        'sesso TEXT CHECK (sesso IN (''M'', ''F'', ''X'')) DEFAULT ''X'',' ...
        'reparto_id INTEGER REFERENCES reparti(id) ON DELETE SET NULL' ...
        ');' ...
        ]);

    execute(conn, [ ...
        'CREATE TABLE tipi_esame (' ...
        'id INTEGER PRIMARY KEY AUTOINCREMENT,' ...
        'codice TEXT NOT NULL UNIQUE,' ...
        'nome TEXT NOT NULL,' ...
        'unita_ref TEXT NOT NULL,' ...
        'valore_min REAL,' ...
        'valore_max REAL' ...
        ');' ...
        ]);

    execute(conn, [ ...
        'CREATE TABLE visite (' ...
        'id INTEGER PRIMARY KEY AUTOINCREMENT,' ...
        'paziente_id INTEGER NOT NULL REFERENCES pazienti(id) ON DELETE CASCADE,' ...
        'medico_id INTEGER NOT NULL REFERENCES medici(id) ON DELETE RESTRICT,' ...
        'data_visita TEXT NOT NULL,' ...
        'motivo TEXT' ...
        ');' ...
        ]);

    execute(conn, [ ...
        'CREATE TABLE esami_lab (' ...
        'id INTEGER PRIMARY KEY AUTOINCREMENT,' ...
        'visita_id INTEGER NOT NULL REFERENCES visite(id) ON DELETE CASCADE,' ...
        'tipo_esame_id INTEGER NOT NULL REFERENCES tipi_esame(id) ON DELETE RESTRICT,' ...
        'valore REAL NOT NULL,' ...
        'unita TEXT NOT NULL,' ...
        'data_risultato TEXT NOT NULL,' ...
        'note TEXT' ...
        ');' ...
        ]);

    % --- Dati di esempio (stesso contenuto logico di sql/lab07_schema.sql) ---

    execute(conn, 'INSERT INTO reparti (nome, piano, descrizione) VALUES (''Biochimica clinica'', 2, ''Laboratorio centrale: biochimica, immunologia, ormoni'');');
    execute(conn, 'INSERT INTO reparti (nome, piano, descrizione) VALUES (''Ematologia'', 4, ''Emocromo, coagulazione, emoglobinurie'');');
    execute(conn, 'INSERT INTO reparti (nome, piano, descrizione) VALUES (''Medicina interna'', 3, ''Degenza e follow-up metabolico'');');

    execute(conn, 'INSERT INTO medici (nome, cognome, reparto_id, specialita) VALUES (''Anna'', ''Rossi'', 1, ''Patologia clinica'');');
    execute(conn, 'INSERT INTO medici (nome, cognome, reparto_id, specialita) VALUES (''Luca'', ''Gallo'', 1, ''Endocrinologia e diabetologia'');');
    execute(conn, 'INSERT INTO medici (nome, cognome, reparto_id, specialita) VALUES (''Chiara'', ''Marta'', 3, ''Medicina interna'');');
    execute(conn, 'INSERT INTO medici (nome, cognome, reparto_id, specialita) VALUES (''Filippo'', ''Neri'', 2, ''Ematologia clinica'');');

    execute(conn, 'INSERT INTO pazienti (nome, cognome, anno_nascita, sesso, reparto_id) VALUES (''Giulia'', ''Verdi'', 1992, ''F'', 1);');
    execute(conn, 'INSERT INTO pazienti (nome, cognome, anno_nascita, sesso, reparto_id) VALUES (''Marco'', ''Bianchi'', 1985, ''M'', 1);');
    execute(conn, 'INSERT INTO pazienti (nome, cognome, anno_nascita, sesso, reparto_id) VALUES (''Laura'', ''Neri'', 2001, ''F'', 2);');
    execute(conn, 'INSERT INTO pazienti (nome, cognome, anno_nascita, sesso, reparto_id) VALUES (''Paolo'', ''Blu'', 1978, ''M'', 3);');

    execute(conn, 'INSERT INTO tipi_esame (codice, nome, unita_ref, valore_min, valore_max) VALUES (''GLU'', ''Glicemia'', ''mg/dL'', 70, 100);');
    execute(conn, 'INSERT INTO tipi_esame (codice, nome, unita_ref, valore_min, valore_max) VALUES (''HGB'', ''Emoglobina'', ''g/dL'', 12.0, 16.0);');
    execute(conn, 'INSERT INTO tipi_esame (codice, nome, unita_ref, valore_min, valore_max) VALUES (''CHOL'', ''Colesterolo totale'', ''mg/dL'', NULL, 200);');
    execute(conn, 'INSERT INTO tipi_esame (codice, nome, unita_ref, valore_min, valore_max) VALUES (''PCR'', ''PCR quantitativa'', ''mg/dL'', NULL, 5);');
    execute(conn, 'INSERT INTO tipi_esame (codice, nome, unita_ref, valore_min, valore_max) VALUES (''LDH'', ''LDH'', ''U/L'', 140, 280);');
    execute(conn, 'INSERT INTO tipi_esame (codice, nome, unita_ref, valore_min, valore_max) VALUES (''FERR'', ''Ferritina'', ''ng/mL'', 20, 300);');
    execute(conn, 'INSERT INTO tipi_esame (codice, nome, unita_ref, valore_min, valore_max) VALUES (''CREA'', ''Creatinina'', ''umol/L'', 59, 104);');
    execute(conn, 'INSERT INTO tipi_esame (codice, nome, unita_ref, valore_min, valore_max) VALUES (''PAS'', ''Pressione sistolica'', ''mmHg'', 90, 140);');

    execute(conn, 'INSERT INTO visite (paziente_id, medico_id, data_visita, motivo) VALUES (1, 1, ''2025-01-10'', ''Controllo metabolico e profilo lipidico'');');
    execute(conn, 'INSERT INTO visite (paziente_id, medico_id, data_visita, motivo) VALUES (1, 2, ''2025-03-02'', ''Follow-up glicemia e colesterolo'');');
    execute(conn, 'INSERT INTO visite (paziente_id, medico_id, data_visita, motivo) VALUES (2, 1, ''2025-02-15'', ''Primo accesso per iperglicemia'');');
    execute(conn, 'INSERT INTO visite (paziente_id, medico_id, data_visita, motivo) VALUES (3, 3, ''2025-04-01'', ''Screening pre-operatorio'');');
    execute(conn, 'INSERT INTO visite (paziente_id, medico_id, data_visita, motivo) VALUES (4, 4, ''2025-04-05'', ''Controllo post-dimissioni'');');
    execute(conn, 'INSERT INTO visite (paziente_id, medico_id, data_visita, motivo) VALUES (2, 2, ''2025-05-10'', ''Visita ambulatoriale diabetologica'');');

    execute(conn, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (1, 1, 92.0, ''mg/dL'', ''2025-01-10'', NULL);');
    execute(conn, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (1, 7, 88.0, ''umol/L'', ''2025-01-10'', ''eGFR stabile'');');
    execute(conn, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato, note) VALUES (2, 1, 108.0, ''mg/dL'', ''2025-03-02'', ''a digiuno'');');
    execute(conn, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato) VALUES (2, 3, 195.0, ''mg/dL'', ''2025-03-02'');');
    execute(conn, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato) VALUES (2, 8, 122.0, ''mmHg'', ''2025-03-02'', ''PA al momento del prelievo'');');
    execute(conn, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato) VALUES (3, 1, 126.0, ''mg/dL'', ''2025-02-15'');');
    execute(conn, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato) VALUES (3, 2, 14.1, ''g/dL'', ''2025-02-15'');');
    execute(conn, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato) VALUES (4, 1, 88.0, ''mg/dL'', ''2025-04-01'');');
    execute(conn, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato) VALUES (4, 8, 118.0, ''mmHg'', ''2025-04-01'');');
    execute(conn, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato) VALUES (5, 2, 13.2, ''g/dL'', ''2025-04-05'');');
    execute(conn, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato) VALUES (5, 4, 2.1, ''mg/dL'', ''2025-04-05'', ''infiammazione lieve'');');
    execute(conn, 'INSERT INTO esami_lab (visita_id, tipo_esame_id, valore, unita, data_risultato) VALUES (1, 3, 178.0, ''mg/dL'', ''2025-01-10'', ''primo campione del profilo'');');

    close(conn);
end
