% Esercizio 5 — sqlwrite: due nuovi esami per il paziente_id = 2
%
% Ricrea il database, inserisce due righe da table MATLAB, verifica con fetch.

thisDir = fileparts(mfilename('fullpath'));
labDir = fileparts(thisDir);
addpath(fullfile(labDir, 'codice'));
dbPath = lab07_create_fresh_database(labDir);

conn = sqlite(dbPath);
T = table( ...
    [2; 2], ...
    {'LDH'; 'PCR'}, ...
    [230; 0.4], ...
    {'U/L'; 'mg/dL'}, ...
    {'2025-05-10'; '2025-05-10'}, ...
    'VariableNames', {'paziente_id', 'nome_esame', 'valore', 'unita', 'data_esame'} ...
    );
sqlwrite(conn, 'esami_lab', T);
T2 = fetch(conn, [ ...
    'SELECT * FROM esami_lab WHERE paziente_id = 2 ' ...
    'AND nome_esame IN (''LDH'', ''PCR'') ORDER BY nome_esame;' ...
    ]);
close(conn);

disp('--- Esami LDH e PCR per paziente 2 ---');
disp(T2);
