% ESERCIZIO 10 — Query più ricche: DISTINCT, LIKE, IN, CASE, HAVING, sottoquery
%
% Obiettivo: vedere più forme di SELECT su un database con più tabelle.

cartellaScript = fileparts(mfilename('fullpath'));
cartellaLab = fileparts(cartellaScript);
addpath(fullfile(cartellaLab, 'codice'));

run(fullfile(cartellaLab, 'codice', 'lab07_create_fresh_database.m'));
percorsoDb = dbPath;
conn = sqlite(percorsoDb);
execute(conn, 'PRAGMA foreign_keys=ON;');

% DISTINCT elimina duplicati: qui mostra quali reparti compaiono nelle visite.
q1 = [ ...
    'SELECT DISTINCT r.nome AS reparto ' ...
    'FROM visite v ' ...
    'JOIN medici m ON m.id = v.medico_id ' ...
    'JOIN reparti r ON r.id = m.reparto_id ' ...
    'ORDER BY r.nome' ...
    ];
disp('--- Reparti coinvolti nelle visite (DISTINCT) ---');
disp(fetch(conn, q1));

% LIKE cerca testo parziale: pazienti il cui cognome contiene "i".
q2 = [ ...
    'SELECT id, nome, cognome, anno_nascita ' ...
    'FROM pazienti ' ...
    'WHERE cognome LIKE ''%i%'' ' ...
    'ORDER BY cognome' ...
    ];
disp('--- Pazienti con cognome che contiene la lettera i (LIKE) ---');
disp(fetch(conn, q2));

% IN filtra su un insieme di codici esame.
q3 = [ ...
    'SELECT cognome, nome, codice, esame, valore, unita, data_risultato ' ...
    'FROM v_esami_completi ' ...
    'WHERE codice IN (''GLU'', ''CHOL'', ''TSH'') ' ...
    'ORDER BY cognome, data_risultato' ...
    ];
disp('--- Esami selezionati con IN (GLU, CHOL, TSH) ---');
disp(fetch(conn, q3));

% CASE costruisce una colonna derivata: stato rispetto al range di riferimento.
q4 = [ ...
    'SELECT cognome, codice, valore, unita, valore_min, valore_max, ' ...
    'CASE ' ...
    'WHEN valore_min IS NOT NULL AND valore < valore_min THEN ''basso'' ' ...
    'WHEN valore_max IS NOT NULL AND valore > valore_max THEN ''alto'' ' ...
    'ELSE ''nel range'' END AS interpretazione ' ...
    'FROM v_esami_completi ' ...
    'ORDER BY interpretazione, cognome, codice' ...
    ];
disp('--- Interpretazione didattica con CASE ---');
disp(fetch(conn, q4));

% GROUP BY + HAVING: HAVING filtra i gruppi dopo l aggregazione.
q5 = [ ...
    'SELECT cognome, nome, COUNT(*) AS n_esami ' ...
    'FROM v_esami_completi ' ...
    'GROUP BY cognome, nome ' ...
    'HAVING COUNT(*) >= 4 ' ...
    'ORDER BY n_esami DESC' ...
    ];
disp('--- Pazienti con almeno 4 risultati di laboratorio (GROUP BY + HAVING) ---');
disp(fetch(conn, q5));

% Sottoquery: pazienti che hanno almeno una glicemia sopra il valore massimo.
q6 = [ ...
    'SELECT p.id, p.nome, p.cognome ' ...
    'FROM pazienti p ' ...
    'WHERE p.id IN ( ' ...
    '  SELECT v.paziente_id ' ...
    '  FROM visite v ' ...
    '  JOIN esami_lab e ON e.visita_id = v.id ' ...
    '  JOIN tipi_esame t ON t.id = e.tipo_esame_id ' ...
    '  WHERE t.codice = ''GLU'' AND e.valore > t.valore_max ' ...
    ') ' ...
    'ORDER BY p.cognome' ...
    ];
disp('--- Pazienti con almeno una glicemia sopra range (sottoquery) ---');
disp(fetch(conn, q6));

close(conn);
